# Generated by Django 2.2.1 on 2019-09-23 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190922_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_signin_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上次登录时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=120, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个性签名'),
        ),
    ]
