# Generated by Django 2.2.1 on 2019-09-20 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=20, verbose_name='aid')),
                ('name', models.CharField(max_length=50, verbose_name='视频名称')),
                ('tags', models.CharField(max_length=10, verbose_name='标签')),
                ('url', models.CharField(max_length=100, verbose_name='链接')),
                ('cover', models.CharField(max_length=100, verbose_name='封面')),
                ('desc', models.CharField(max_length=1000, verbose_name='说明')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
