# Generated by Django 2.2.1 on 2019-09-20 03:47

import Photo.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图册名称')),
                ('tags', models.CharField(max_length=10, verbose_name='标签')),
                ('image', models.ImageField(upload_to=Photo.models.upload_to, verbose_name='照片')),
                ('desc', models.CharField(max_length=1000, verbose_name='说明')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '图册',
                'verbose_name_plural': '图册',
            },
        ),
    ]
